spring:
  datasource:
    url: jdbc:postgresql://localhost:5050/todo_db
    username: ${PG_USER}
    password: ${PG_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update 
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
server:
  port: 8080

# Dev CORS, allow Vite on 5173
app:
  cors:
    origins: "http://localhost:5173"
